ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # Filter update rate
    two_d_mode: true  # Ignore Z-axis for 2D robots
    map_frame: ekf_map
    odom_frame: ekf_odom
    base_link_frame: base_link
    world_frame: ekf_map

    # Odometry input
    odom0: /diff_cont/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    # IMU input (if available)
    imu0: /demo/imu
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true, false, false]
    imu0_differential: true
